# Generated by Django 3.2.10 on 2022-03-18 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vouchers', '0001_initial'),
        ('accounts', '0001_initial'),
        ('bkash', '0001_initial'),
        ('payments', '0001_initial'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(max_length=1)),
                ('bk_payment_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bkash.paymentbkashagent')),
                ('collection_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('general_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.generalvoucher')),
                ('investment_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.investment')),
                ('payment_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
        ),
    ]
