# Generated by Django 3.2.10 on 2022-03-18 04:37

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LC', '0001_initial'),
        ('vouchers', '0001_initial'),
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        ('bkash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_to', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('CQ', 'Cheque'), ('CA', 'Cash'), ('ONL', 'Online'), ('PO', 'Pay Order'), ('BK', 'Bkash')], default=('CA', 'Cash'), max_length=10)),
                ('cheque_PO_ONL_no', models.IntegerField(blank=True, null=True)),
                ('cheque_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_amount', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('date_time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lc_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LC.lc')),
                ('payed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_for_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.persons')),
                ('payment_from_account', models.ForeignKey(default=accounts.models.default_account, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bkash.bkashtransaction')),
                ('voucher_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.buyvoucher')),
            ],
        ),
    ]
