# Generated by Django 3.0.6 on 2020-06-15 13:14

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20200524_0013'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_no',
            field=models.CharField(default=payments.models.increment_payment_number, max_length=50, unique=True),
        ),
    ]
