# Generated by Django 3.0.6 on 2020-08-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_for_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('CQ', 'Cheque'), ('CA', 'Cash'), ('ONL', 'Online'), ('PO', 'Pay Order')], default=('CA', 'Cash'), max_length=10),
        ),
    ]
