# Generated by Django 3.0.6 on 2020-08-26 08:42

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0002_auto_20200826_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_from_account',
            field=models.ForeignKey(default=accounts.models.default_account, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
        ),
    ]
