# Generated by Django 3.0.6 on 2020-09-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20200826_1438'),
        ('payments', '0003_auto_20200826_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.BuyVoucher'),
        ),
    ]
