# Generated by Django 3.0.6 on 2020-06-15 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200611_2058'),
        ('vouchers', '0010_auto_20200528_1816'),
        ('payments', '0003_auto_20200615_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.BuyVoucher'),
        ),
    ]
