# Generated by Django 3.0.6 on 2020-09-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200830_1844'),
        ('payments', '0004_auto_20200919_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payed_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_for_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons'),
        ),
    ]
