# Generated by Django 3.1.1 on 2020-10-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0013_bkashtransaction_transaction_type'),
        ('payments', '0005_auto_20200919_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bkash.bkashtransaction'),
        ),
    ]
