# Generated by Django 3.1.4 on 2021-04-02 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LC', '0004_auto_20210401_1654'),
        ('payments', '0009_auto_20210306_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='lc_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LC.lc'),
        ),
    ]
