# Generated by Django 3.1.4 on 2021-05-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_bank'),
        ('payments', '0010_auto_20210402_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_for_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.persons'),
        ),
    ]
