# Generated by Django 3.0.6 on 2021-10-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0025_remove_salevoucher_voucher_number'),
        ('payments', '0012_remove_payment_payment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='voucher_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.BuyVoucher'),
        ),
    ]
