# Generated by Django 3.0.6 on 2020-10-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountledger',
            name='account',
        ),
    ]
