# Generated by Django 3.0.6 on 2020-10-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ledger', '0002_remove_accountledger_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
        ),
    ]
