# Generated by Django 3.0.6 on 2020-10-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200919_0019'),
        ('bkash', '0010_bkashtransaction_ordered_by'),
        ('accounts', '0001_initial'),
        ('vouchers', '0004_auto_20200920_2228'),
        ('collection', '0001_initial'),
        ('ledger', '0003_accountledger_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountledger',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountledger',
            name='voucher',
        ),
        migrations.AddField(
            model_name='accountledger',
            name='bk_payment_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bkash.PaymentBkashAgent'),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='collection_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Collection'),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='general_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.GeneralVoucher'),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='investment_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Investment'),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='payment_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Payment'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='type',
            field=models.CharField(max_length=5),
        ),
    ]
