# Generated by Django 3.0.6 on 2020-10-31 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20201029_1142'),
        ('ledger', '0004_auto_20201002_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='salary_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.SalaryPayment'),
        ),
    ]
