# Generated by Django 3.1.4 on 2020-12-23 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_accountledger_salary_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountledger',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
