# Generated by Django 3.1.4 on 2021-04-01 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LC', '0004_auto_20210401_1654'),
        ('ledger', '0006_auto_20201223_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='lc_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='LC.lc'),
        ),
    ]
