# Generated by Django 3.1.4 on 2021-04-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_accountledger_lc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountledger',
            name='lc_number',
        ),
    ]
