# Generated by Django 3.2.10 on 2022-03-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('challan_serial', models.CharField(max_length=10, null=True, unique=True)),
                ('weight_adjusted', models.FloatField(max_length=10)),
                ('weight_of_each_bag', models.FloatField(default=0)),
                ('number_of_bag', models.FloatField(max_length=10)),
                ('number_of_vehicle', models.IntegerField(blank=True, null=True)),
                ('name_of_driver', models.CharField(blank=True, max_length=200, null=True)),
                ('driver_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('challan_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.companies')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('sub_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, to='organizations.persons')),
            ],
        ),
    ]
