# Generated by Django 3.0.6 on 2020-08-26 08:26

import challan.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(default=challan.models.increment_challan_number, max_length=10, unique=True)),
                ('weight', models.FloatField(max_length=10)),
                ('number_of_bag', models.FloatField(max_length=10)),
                ('number_of_vehicle', models.IntegerField(blank=True, null=True)),
                ('name_of_driver', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buyer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Companies')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
