# Generated by Django 3.0.6 on 2020-05-28 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_auto_20200524_0013'),
        ('products', '0002_auto_20200521_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=10, unique=True)),
                ('weight_per_bag', models.FloatField(max_length=10)),
                ('number_of_bag', models.FloatField(max_length=10)),
                ('number_of_vehicle', models.IntegerField(blank=True, null=True)),
                ('name_of_driver', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('buyer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Companies')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
