# Generated by Django 3.0.6 on 2020-07-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0003_auto_20200528_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='weight_per_bag',
            new_name='weight',
        ),
    ]
