# Generated by Django 3.1.4 on 2021-05-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization'),
        ('challan', '0003_challan_challan_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
