# Generated by Django 3.1.4 on 2021-05-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0004_challan_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
