# Generated by Django 3.1.4 on 2021-05-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0005_auto_20210509_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_serial',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
