# Generated by Django 3.1.4 on 2021-05-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0006_auto_20210514_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='buyer_name',
        ),
    ]
