# Generated by Django 3.1.4 on 2021-05-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0007_remove_challan_buyer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='weight',
            new_name='weight_adjusted',
        ),
        migrations.AddField(
            model_name='challan',
            name='weight_of_each_bag',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
