# Generated by Django 3.1.4 on 2021-05-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0008_auto_20210514_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='weight_of_each_bag',
            field=models.FloatField(default=0),
        ),
    ]
