# Generated by Django 3.1.4 on 2021-05-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0009_auto_20210515_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_serial',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
