# Generated by Django 3.1.4 on 2021-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0010_auto_20210515_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='driver_phone_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
