# Generated by Django 3.1.4 on 2021-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0014_auto_20210516_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
