# Generated by Django 3.0.6 on 2021-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0016_auto_20210517_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
