# Generated by Django 3.0.6 on 2021-06-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0017_auto_20210517_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='reference',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
