# Generated by Django 3.2.8 on 2021-10-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0018_challan_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='challan_no',
        ),
    ]
