# Generated by Django 3.0.6 on 2020-06-15 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20200611_2058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vouchers', '0010_auto_20200528_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_no', models.CharField(max_length=10)),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('collection_mode', models.CharField(choices=[('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Online', 'Online'), ('Pay Order', 'Pay Order')], max_length=10)),
                ('cheque_PO_ONL_no', models.IntegerField(blank=True, null=True)),
                ('cheque_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_amount', models.FloatField()),
                ('collection_status', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collection_to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
                ('sale_voucher_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.SaleVoucher')),
            ],
        ),
    ]
