# Generated by Django 3.1.1 on 2020-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sale_type',
            field=models.CharField(choices=[('SALE', 'SALE'), ('LOCAL SALE', 'LOCAL SALE')], default=('LOCAL SALE', 'LOCAL SALE'), max_length=10),
        ),
    ]
