# Generated by Django 3.0.6 on 2020-06-16 10:35

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_no',
            field=models.CharField(default=collection.models.increment_collection_number, max_length=10, unique=True),
        ),
    ]
