# Generated by Django 3.1.1 on 2020-10-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_generalvoucher_transaction'),
        ('collection', '0003_collection_local_sale_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='sale_voucher_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.salevoucher'),
        ),
    ]
