# Generated by Django 3.1.1 on 2020-10-06 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_generalvoucher_transaction'),
        ('organizations', '0002_auto_20200830_1844'),
        ('local_sale', '0002_auto_20201002_1248'),
        ('collection', '0004_auto_20201005_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collected_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.persons'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='local_sale_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local_sale.localsale'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sale_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.salevoucher'),
        ),
    ]
