# Generated by Django 3.1.1 on 2020-10-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200830_1844'),
        ('collection', '0005_auto_20201006_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collected_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.persons'),
            preserve_default=False,
        ),
    ]
