# Generated by Django 3.1.1 on 2020-12-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_sale', '0004_auto_20201011_1532'),
        ('vouchers', '0008_auto_20201207_0249'),
        ('collection', '0006_auto_20201006_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='local_sale_voucher_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='local_sale.localsale'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sale_voucher_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.salevoucher'),
        ),
    ]
