# Generated by Django 3.0.6 on 2021-05-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20201221_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collected_from',
        ),
    ]
