# Generated by Django 3.0.6 on 2021-10-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_remove_collection_collected_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_no',
        ),
    ]
