# Generated by Django 3.0.6 on 2020-08-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=200, unique=True)),
                ('company_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('nid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact_number', models.CharField(max_length=17, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('nid_photo', models.ImageField(blank=True, upload_to='nid_photo')),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Companies')),
            ],
        ),
    ]
