# Generated by Django 3.2.10 on 2022-03-18 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(default='Contact Person', max_length=200)),
                ('designation', models.CharField(default='Designation', max_length=200)),
                ('company_address', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('proprietor', models.CharField(default='N/A', max_length=50)),
                ('signature', models.ImageField(blank=True, upload_to='company_docs')),
                ('pad', models.ImageField(blank=True, upload_to='company_docs')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('nid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('nid_photo', models.ImageField(blank=True, upload_to='nid_photo')),
                ('person_photo', models.ImageField(default='default.jpg', upload_to='person_photo')),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.companies')),
            ],
        ),
    ]
