# Generated by Django 3.0.6 on 2020-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='nid_photo',
            field=models.ImageField(blank=True, upload_to='nid_photo'),
        ),
    ]
