# Generated by Django 3.1.1 on 2020-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200830_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='person_photo',
            field=models.ImageField(blank=True, upload_to='person_photo'),
        ),
    ]
