# Generated by Django 3.0.6 on 2020-05-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_companies_persons'),
        ('vouchers', '0006_auto_20200523_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizations',
        ),
        migrations.AddField(
            model_name='persons',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Companies'),
        ),
    ]
