# Generated by Django 3.0.6 on 2020-05-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200523_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name_of_company',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
