# Generated by Django 3.1.4 on 2021-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='proprietor',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
