# Generated by Django 3.0.6 on 2021-09-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20210515_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='contact_person',
            field=models.CharField(default='Contact Person', max_length=200),
        ),
        migrations.AddField(
            model_name='companies',
            name='designation',
            field=models.CharField(default='Designation', max_length=200),
        ),
    ]
