# Generated by Django 3.1.1 on 2021-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LC', '0004_auto_20210401_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='date_time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
