# Generated by Django 3.1.1 on 2021-05-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LC', '0005_auto_20210510_2328'),
        ('LC', '0005_auto_20210509_1230'),
    ]

    operations = [
    ]
