# Generated by Django 3.0.6 on 2020-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='M/S FATEMA ENTERPRISE', max_length=50, null=True)),
                ('account_no', models.CharField(max_length=50, null=True, unique=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('bank_branch', models.CharField(max_length=50, null=True)),
                ('opening_balance', models.FloatField(default=0, null=True)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OtherAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='CASH IN HAND', max_length=50, null=True, unique=True)),
                ('opening_balance', models.FloatField(default=0, null=True)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
