# Generated by Django 3.2.10 on 2022-03-18 04:37

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='M/S FATEMA ENTERPRISE', max_length=50, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_of_investment', models.CharField(default='Daily Cash Invest', max_length=200)),
                ('investing_amount', models.FloatField()),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('investing_from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investing_from_account', to='accounts.accounts')),
                ('investing_to_account', models.ForeignKey(default=accounts.models.default_account, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investing_to_account', to='accounts.accounts')),
            ],
        ),
    ]
