# Generated by Django 3.0.6 on 2020-10-08 22:28

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investing_from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investing_from_account', to='accounts.Accounts'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investing_to_account',
            field=models.ForeignKey(default=accounts.models.default_account, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investing_to_account', to='accounts.Accounts'),
        ),
    ]
