# Generated by Django 3.1.1 on 2020-10-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201009_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='remaining_balance',
        ),
    ]
