# Generated by Django 3.0.6 on 2020-06-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200607_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='remaining_balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investing_to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
        ),
    ]
