# Generated by Django 3.0.6 on 2020-06-08 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200608_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='date_dated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='date_dated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='remaining_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
