# Generated by Django 3.0.6 on 2021-05-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_investment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='date_added',
        ),
    ]
