# Generated by Django 3.0.6 on 2021-05-17 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_investment_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
