# Generated by Django 3.0.6 on 2020-06-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20200609_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='date_dated',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_dated',
        ),
    ]
