# Generated by Django 3.0.6 on 2020-09-27 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import local_sale.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_auto_20200830_1844'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_no', models.CharField(default=local_sale.models.increment_local_sale_no, max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Persons')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('weight', models.FloatField()),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('sale_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_sale.LocalSale')),
            ],
        ),
    ]
