# Generated by Django 3.2.10 on 2022-03-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transport_charge', models.FloatField(blank=True, default=0)),
                ('transport_charge_payee', models.CharField(blank=True, choices=[('CUSTOMER', 'CUSTOMER'), ('SUPPLIER', 'SUPPLIER')], default=('SUPPLIER', 'SUPPLIER'), max_length=8)),
                ('previous_due', models.FloatField(blank=True, default=0)),
                ('date_time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('discount', models.FloatField(blank=True, default=0)),
                ('remarks', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('business_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('buyer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.persons')),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.companies')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('weight', models.FloatField()),
                ('number_of_bag', models.FloatField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('sale_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_sale.localsale')),
            ],
        ),
    ]
