# Generated by Django 3.0.6 on 2020-09-30 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import local_sale.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local_sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='localsale',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='localsale',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localsale',
            name='remarks',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_bag',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='localsale',
            name='sale_no',
            field=models.CharField(default=local_sale.models.increment_local_sale_no, max_length=10, unique=True),
        ),
    ]
