# Generated by Django 3.1.1 on 2020-10-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_sale', '0002_auto_20201002_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsale',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
