# Generated by Django 3.0.6 on 2021-09-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_sale', '0004_auto_20201011_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localsale',
            name='sale_no',
        ),
    ]
