# Generated by Django 3.1.1 on 2021-09-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20210919_2339'),
        ('local_sale', '0005_remove_localsale_sale_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsale',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
    ]
