# Generated by Django 3.2.10 on 2022-03-18 04:37

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('bkash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('designation', models.CharField(default='Worker', max_length=50)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('NID', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True)),
                ('hourly_rate', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(default='default.jpg', upload_to='employee_photo')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_table_name', models.CharField(default='Day Time', max_length=10, unique=True)),
                ('in_time', models.TimeField(default='09:00')),
                ('out_time', models.TimeField(default='17:00')),
                ('weekend', models.CharField(choices=[('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday')], default=('FRI', 'Friday'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AUG', 'AUG'), ('SEP', 'SEP'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], max_length=20, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('CQ', 'Cheque'), ('CA', 'Cash'), ('ONL', 'Online'), ('PO', 'Pay Order'), ('BK', 'Bkash')], default=('CA', 'Cash'), max_length=10)),
                ('cheque_PO_ONL_no', models.IntegerField(blank=True, null=True)),
                ('cheque_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.employee')),
                ('payed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_from_account', models.ForeignKey(default=accounts.models.default_account, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bkash.bkashtransaction')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.Empty, to='payroll.timetable'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TimeField(default=django.utils.timezone.now)),
                ('out_time', models.TimeField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=False)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.day')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
