# Generated by Django 3.1.1 on 2020-10-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='NID',
            field=models.IntegerField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Worker', max_length=50),
        ),
    ]
