# Generated by Django 3.1.1 on 2020-10-19 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20201019_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_table_name', models.CharField(default='Day Time', max_length=20)),
                ('in_time', models.TimeField(default=django.utils.timezone.now)),
                ('out_time', models.TimeField(default=django.utils.timezone.now)),
                ('weekend', models.CharField(choices=[('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday')], default=('FRI', 'Friday'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('in_time', models.TimeField(default=django.utils.timezone.now)),
                ('out_time', models.TimeField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='time_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, to='payroll.timetable'),
        ),
    ]
