# Generated by Django 3.0.6 on 2020-10-19 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20201019_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='NID',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
