# Generated by Django 3.1.1 on 2020-10-22 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20201021_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='in_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='out_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_table_name',
            field=models.CharField(default='Day Time', max_length=10, unique=True),
        ),
    ]
