# Generated by Django 3.1.1 on 2020-10-29 11:41

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201010_1025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bkash', '0013_bkashtransaction_transaction_type'),
        ('payroll', '0007_auto_20201022_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AUG', 'AUG'), ('SEP', 'SEP'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], max_length=20, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=datetime.datetime(2020, 10, 29, 11, 41, 17, 345253))),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('CQ', 'Cheque'), ('CA', 'Cash'), ('ONL', 'Online'), ('PO', 'Pay Order'), ('BK', 'Bkash')], default=('CA', 'Cash'), max_length=10)),
                ('cheque_PO_ONL_no', models.IntegerField(blank=True, null=True)),
                ('cheque_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.employee')),
                ('payed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_from_account', models.ForeignKey(default=accounts.models.default_account, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bkash.bkashtransaction')),
            ],
        ),
    ]
