# Generated by Django 3.1.1 on 2020-10-29 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_salarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
