# Generated by Django 3.1.4 on 2020-12-28 01:02

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20201029_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.Empty, to='payroll.timetable'),
        ),
    ]
