# Generated by Django 3.0.6 on 2020-05-22 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20200521_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.IntegerField()),
                ('seller_name', models.CharField(max_length=200)),
                ('weight', models.FloatField(max_length=10)),
                ('number_of_bag', models.FloatField(max_length=10)),
                ('number_of_vehicle', models.IntegerField()),
                ('rate', models.FloatField(max_length=10)),
                ('bazar_or_company_name', models.CharField(blank=True, max_length=50)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
