# Generated by Django 3.0.6 on 2020-08-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vouchers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('challan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(default=vouchers.models.increment_sale_number, max_length=10, unique=True)),
                ('per_bag_unloading_cost', models.FloatField(blank=True, default=0, null=True)),
                ('measuring_cost_per_kg', models.FloatField(blank=True, default=0, null=True)),
                ('weight_of_each_bag', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(max_length=10)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('challan_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challan.Challan')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(default=vouchers.models.increment_general_voucher_number, max_length=10, unique=True)),
                ('person_name', models.CharField(max_length=200)),
                ('cost_Descriptions', models.TextField(blank=True, max_length=500, null=True)),
                ('cost_amount', models.FloatField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('from_account', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='BuyVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(default=vouchers.models.increment_buy_voucher_number, max_length=10, unique=True)),
                ('weight', models.FloatField(max_length=10)),
                ('per_bag_unloading_cost', models.FloatField(blank=True, null=True)),
                ('measuring_cost_per_kg', models.FloatField(blank=True, null=True)),
                ('weight_of_each_bag', models.FloatField(blank=True, null=True)),
                ('number_of_bag', models.FloatField(max_length=10)),
                ('number_of_vehicle', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(max_length=10)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('previous_amount', models.FloatField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bazar_or_company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Companies')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('seller_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons')),
            ],
        ),
    ]
