# Generated by Django 3.2.10 on 2022-03-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        ('challan', '0001_initial'),
        ('bkash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_bag_unloading_cost', models.FloatField(default=0)),
                ('measuring_cost_per_kg', models.FloatField(default=0)),
                ('weight_of_each_bag', models.FloatField(default=0)),
                ('weight_adjusted', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('spot_weight', models.FloatField(default=0)),
                ('spot_percentage', models.FloatField(default=0)),
                ('spot_rate', models.FloatField(default=0)),
                ('moisture_weight', models.FloatField(default=0)),
                ('moisture_percentage', models.FloatField(default=0)),
                ('seed_weight', models.FloatField(default=0)),
                ('seed_percentage', models.FloatField(default=0)),
                ('seed_rate', models.FloatField(default=0)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('weight_percentage_TDS', models.FloatField(default=0)),
                ('amount_percentage_TDS', models.FloatField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('challan_no', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='challan.challan')),
            ],
        ),
        migrations.CreateModel(
            name='SaleExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expanse_name', models.CharField(default='Expense 1', max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.salevoucher')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_Descriptions', models.TextField(blank=True, max_length=500, null=True)),
                ('cost_amount', models.FloatField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('business_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('from_account', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('person_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.persons')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bkash.bkashtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='BuyVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_bag_unloading_cost', models.FloatField(blank=True, null=True)),
                ('measuring_cost_per_kg', models.FloatField(blank=True, null=True)),
                ('number_of_vehicle', models.IntegerField(blank=True, null=True)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_amount', models.FloatField(blank=True, default=0, null=True)),
                ('discount', models.FloatField(blank=True, default=0)),
                ('transport_cost', models.FloatField(blank=True, default=0)),
                ('transport_cost_payee', models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default='Buyer', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bazar_or_company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.companies')),
                ('business_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('seller_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.persons')),
            ],
        ),
    ]
