# Generated by Django 3.0.6 on 2020-05-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200522_2045'),
        ('products', '0002_auto_20200521_1621'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyvoucher',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='buyvoucher',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='buyvoucher',
            name='product_name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
        migrations.AddField(
            model_name='buyvoucher',
            name='seller_name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organizations'),
        ),
    ]
