# Generated by Django 3.0.6 on 2020-05-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20200522_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyvoucher',
            old_name='product_name_id',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='buyvoucher',
            old_name='seller_name_id',
            new_name='seller_name',
        ),
    ]
