# Generated by Django 3.0.6 on 2020-05-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200522_2045'),
        ('vouchers', '0003_auto_20200522_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvoucher',
            name='bazar_or_company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='organizations.Organizations'),
        ),
        migrations.AlterField(
            model_name='buyvoucher',
            name='seller_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='organizations.Organizations'),
        ),
    ]
