# Generated by Django 3.0.6 on 2020-10-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0013_bkashtransaction_transaction_type'),
        ('vouchers', '0004_auto_20200920_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvoucher',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bkash.BkashTransaction'),
        ),
    ]
