# Generated by Django 3.0.6 on 2020-05-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200522_2045'),
        ('vouchers', '0004_auto_20200523_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvoucher',
            name='bazar_or_company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='buyvoucher',
            name='seller_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organizations'),
        ),
    ]
