# Generated by Django 3.0.6 on 2020-05-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_companies_persons'),
        ('vouchers', '0005_auto_20200523_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvoucher',
            name='bazar_or_company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Companies'),
        ),
        migrations.AlterField(
            model_name='buyvoucher',
            name='seller_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons'),
        ),
    ]
