# Generated by Django 3.1.1 on 2020-10-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0002_challan_challan_date'),
        ('vouchers', '0005_generalvoucher_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salevoucher',
            name='challan_no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='challan.challan'),
        ),
    ]
