# Generated by Django 3.0.6 on 2020-12-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_auto_20201008_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevoucher',
            name='fotka_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='fotka_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='moisture_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='seed_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
