# Generated by Django 3.0.6 on 2020-05-23 18:13

from django.db import migrations, models
import vouchers.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_auto_20200523_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvoucher',
            name='voucher_number',
            field=models.CharField(default=vouchers.models.increment_buy_voucher_number, max_length=10, unique=True),
        ),
    ]
