# Generated by Django 3.1.4 on 2021-03-16 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_auto_20201207_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyvoucher',
            name='date_time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
