# Generated by Django 3.0.6 on 2020-05-25 07:59

from django.db import migrations, models
import django.utils.timezone
import vouchers.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_auto_20200525_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(default=vouchers.models.increment_general_voucher_number, max_length=10, unique=True)),
                ('person_name', models.CharField(max_length=200)),
                ('cost_Descriptions', models.TextField(blank=True, max_length=1000, null=True)),
                ('cost_amount', models.FloatField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='voucher_number',
            field=models.CharField(default=vouchers.models.increment_sale_number, max_length=10, unique=True),
        ),
    ]
