# Generated by Django 3.0.6 on 2020-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_auto_20200525_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalvoucher',
            name='cost_Descriptions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
