# Generated by Django 3.0.6 on 2021-05-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_buyvoucher_date_time_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salevoucher',
            old_name='fotka_rate',
            new_name='spot_rate',
        ),
        migrations.RenameField(
            model_name='salevoucher',
            old_name='fotka_weight',
            new_name='spot_weight',
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='seed_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='SaleExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.SaleVoucher')),
            ],
        ),
    ]
