# Generated by Django 3.0.6 on 2021-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0010_auto_20210523_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevoucher',
            name='moisture_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='seed_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='spot_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='measuring_cost_per_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='moisture_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='per_bag_unloading_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='seed_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='seed_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='spot_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='spot_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='weight_of_each_bag',
            field=models.FloatField(default=0),
        ),
    ]
