# Generated by Django 3.0.6 on 2020-06-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0010_auto_20200528_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevoucher',
            name='driver_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
