# Generated by Django 3.0.6 on 2021-06-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_auto_20210523_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyvoucher',
            old_name='rate',
            new_name='rate_per_kg',
        ),
    ]
