# Generated by Django 3.0.6 on 2020-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_salevoucher_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salevoucher',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='buyvoucher',
            name='measuring_cost_per_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyvoucher',
            name='per_bag_unloading_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyvoucher',
            name='weight_of_each_bag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='measuring_cost_per_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='per_bag_unloading_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='weight_of_each_bag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
