# Generated by Django 3.0.6 on 2021-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0012_auto_20210604_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyvoucher',
            name='rate_per_mann',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyvoucher',
            name='rate_per_kg',
            field=models.FloatField(),
        ),
    ]
