# Generated by Django 3.0.6 on 2020-06-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0003_auto_20200528_2137'),
        ('vouchers', '0013_auto_20200617_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salevoucher',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='salevoucher',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='salevoucher',
            name='number_of_bag',
        ),
        migrations.RemoveField(
            model_name='salevoucher',
            name='number_of_vehicle',
        ),
        migrations.RemoveField(
            model_name='salevoucher',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='salevoucher',
            name='vehicle_plate_number',
        ),
        migrations.RemoveField(
            model_name='salevoucher',
            name='weight',
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='challan_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challan.Challan'),
        ),
    ]
