# Generated by Django 3.0.6 on 2021-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0013_auto_20210604_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvoucher',
            name='rate_per_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='buyvoucher',
            name='rate_per_mann',
            field=models.FloatField(default=0),
        ),
    ]
