# Generated by Django 3.0.6 on 2021-06-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0014_auto_20210604_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleexpense',
            old_name='name',
            new_name='expanse_name',
        ),
    ]
