# Generated by Django 3.0.6 on 2020-06-17 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0014_auto_20200617_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevoucher',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
