# Generated by Django 3.0.6 on 2020-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0015_auto_20200618_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salevoucher',
            name='measuring_cost_per_kg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='per_bag_unloading_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='weight_of_each_bag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
