# Generated by Django 3.0.6 on 2021-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0015_auto_20210604_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevoucher',
            name='amount_percentage_TDS',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salevoucher',
            name='weight_percentage_TDS',
            field=models.FloatField(default=0),
        ),
    ]
