# Generated by Django 3.0.6 on 2021-08-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0015_auto_20210604_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyvoucher',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
