# Generated by Django 3.0.6 on 2020-06-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0016_auto_20200619_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salevoucher',
            name='measuring_cost_per_kg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='per_bag_unloading_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salevoucher',
            name='weight_of_each_bag',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
