# Generated by Django 3.0.6 on 2021-09-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0017_auto_20210829_0022'),
        ('vouchers', '0016_auto_20210917_1809'),
    ]

    operations = [
    ]
