# Generated by Django 3.1.1 on 2021-09-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20210919_2339'),
        ('vouchers', '0018_merge_20210919_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyvoucher',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
    ]
