# Generated by Django 3.1.1 on 2021-09-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0019_buyvoucher_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevoucher',
            name='weight_adjusted',
            field=models.FloatField(default=0),
        ),
    ]
