# Generated by Django 3.0.6 on 2020-06-19 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0020_auto_20200620_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvoucher',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
