# Generated by Django 3.0.6 on 2021-09-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20210919_2339'),
        ('vouchers', '0020_salevoucher_weight_adjusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvoucher',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organization'),
        ),
    ]
