# Generated by Django 3.0.6 on 2021-10-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0021_generalvoucher_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalvoucher',
            name='voucher_number',
        ),
    ]
