# Generated by Django 3.0.6 on 2020-06-19 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0021_auto_20200620_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvoucher',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
