# Generated by Django 3.0.6 on 2020-06-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0022_auto_20200620_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvoucher',
            name='measuring_cost_per_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyvoucher',
            name='per_bag_unloading_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyvoucher',
            name='weight_of_each_bag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
