# Generated by Django 3.0.6 on 2021-10-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20210919_2339'),
        ('vouchers', '0022_remove_generalvoucher_voucher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalvoucher',
            name='person_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Persons'),
        ),
    ]
