# Generated by Django 3.0.6 on 2021-10-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0023_auto_20211026_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyvoucher',
            name='voucher_number',
        ),
    ]
