# Generated by Django 3.0.6 on 2020-06-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200611_2058'),
        ('vouchers', '0024_auto_20200620_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvoucher',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Accounts'),
        ),
    ]
