# Generated by Django 3.0.6 on 2021-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0025_remove_salevoucher_voucher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleexpense',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleexpense',
            name='expanse_name',
            field=models.CharField(default='Expense 1', max_length=50),
        ),
    ]
