# Generated by Django 3.0.6 on 2020-07-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0025_generalvoucher_from_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyvoucher',
            old_name='weight_per_bag',
            new_name='weight',
        ),
    ]
