# Generated by Django 3.0.6 on 2020-08-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0026_auto_20200728_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyvoucher',
            name='previous_sale_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
