# Generated by Django 3.0.6 on 2020-08-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0027_buyvoucher_previous_sale_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyvoucher',
            name='previous_sale_amount',
        ),
        migrations.AddField(
            model_name='buyvoucher',
            name='previous_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
