# Generated by Django 3.2.10 on 2022-03-18 04:37

import accounts.models
import bkash.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_number', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=14, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BkashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(default=bkash.models.increment_invoice_number, max_length=10, unique=True)),
                ('transaction_type', models.CharField(choices=[('GENERAL', 'GENERAL'), ('PAYMENT', 'PAYMENT')], default='na', max_length=50)),
                ('ordered_by', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_phone_no', models.CharField(max_length=11)),
                ('transaction_amount', models.FloatField()),
                ('transaction_ID', models.CharField(blank=True, max_length=14, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('date_time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bkash.bkashagents')),
                ('payed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.persons')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentBkashAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(default=bkash.models.increment_payment_number, max_length=10, unique=True)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('date_time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bkash.bkashagents')),
                ('payment_from_account', models.ForeignKey(default=accounts.models.default_account, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction_invoice_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bkash.bkashtransaction')),
            ],
        ),
    ]
