# Generated by Django 3.0.6 on 2020-09-18 09:24

import bkash.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_number', models.IntegerField(max_length=11, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.IntegerField(blank=True, max_length=14, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BkashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(default=bkash.models.increment_invoice_number, max_length=10, unique=True)),
                ('payed_to', models.CharField(max_length=50)),
                ('transaction_phone_no', models.IntegerField(max_length=11, unique=True)),
                ('transaction_amount', models.FloatField()),
                ('transaction_ID', models.CharField(blank=True, max_length=14, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('date_time_stamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bkash.BkashAgents')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentBkashAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(default=bkash.models.increment_payment_number, max_length=10)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateField(auto_now=True)),
                ('date_time_stamp', models.DateTimeField(auto_now=True)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bkash.BkashAgents')),
                ('transaction_invoice_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bkash.BkashTransaction')),
            ],
        ),
    ]
