# Generated by Django 3.0.6 on 2020-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashagents',
            name='agent_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='bkashagents',
            name='contact_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
