# Generated by Django 3.0.6 on 2020-09-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0002_auto_20200918_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bkashtransaction',
            old_name='date',
            new_name='transaction_date',
        ),
    ]
