# Generated by Django 3.0.6 on 2020-09-18 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0003_auto_20200918_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashtransaction',
            name='date_time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bkashtransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bkashtransaction',
            name='transaction_phone_no',
            field=models.CharField(max_length=11),
        ),
    ]
