# Generated by Django 3.0.6 on 2020-09-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200830_1844'),
        ('bkash', '0004_auto_20200918_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashtransaction',
            name='payed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons'),
        ),
    ]
