# Generated by Django 3.0.6 on 2020-09-18 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0005_auto_20200919_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbkashagent',
            name='date_time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentbkashagent',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
