# Generated by Django 3.0.6 on 2020-09-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0007_paymentbkashagent_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbkashagent',
            name='transaction_invoice_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bkash.BkashTransaction'),
        ),
    ]
