# Generated by Django 3.0.6 on 2020-09-19 18:47

import bkash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0008_auto_20200919_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbkashagent',
            name='payment_no',
            field=models.CharField(default=bkash.models.increment_payment_number, max_length=10, unique=True),
        ),
    ]
