# Generated by Django 3.0.6 on 2020-09-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0009_auto_20200920_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkashtransaction',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
