# Generated by Django 3.0.6 on 2020-10-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bkash', '0010_bkashtransaction_ordered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbkashagent',
            name='payment_from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
        ),
    ]
