# Generated by Django 3.0.6 on 2020-10-02 12:59

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bkash', '0011_paymentbkashagent_payment_from_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbkashagent',
            name='payment_from_account',
            field=models.ForeignKey(default=accounts.models.default_account, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
        ),
    ]
