# Generated by Django 3.0.6 on 2020-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0012_auto_20201002_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('PAYMENT', 'PAYMENT')], default=('GENERAL', 'GENERAL'), max_length=10),
        ),
    ]
