# Generated by Django 3.0.6 on 2020-05-28 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200521_1621'),
        ('organizations', '0005_auto_20200524_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=10, unique=True)),
                ('total_weight', models.FloatField(max_length=10)),
                ('rate_per_kg', models.FloatField(max_length=10)),
                ('percentage_of_fotka', models.FloatField(max_length=10)),
                ('percentage_of_moisture', models.FloatField(max_length=10)),
                ('delivery_deadline', models.DateField(default=django.utils.timezone.now)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Companies')),
                ('person_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Persons')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
