# Generated by Django 3.2.10 on 2022-03-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default=orders.models.increment_order_number, max_length=10, unique=True)),
                ('total_weight', models.FloatField(max_length=10)),
                ('rate_per_kg', models.FloatField(max_length=10)),
                ('percentage_of_fotka', models.FloatField(max_length=10)),
                ('percentage_of_moisture', models.FloatField(max_length=10)),
                ('delivery_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='Processing', max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.companies')),
                ('person_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.persons')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
