# Generated by Django 3.0.6 on 2020-05-29 18:12

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_no',
            field=models.CharField(default=orders.models.increment_order_number, max_length=10, unique=True),
        ),
    ]
