# Generated by Django 3.0.6 on 2020-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200530_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Online', 'Online'), ('Pay Order', 'Pay Order')], max_length=20, null=True),
        ),
    ]
