# Generated by Django 3.0.6 on 2021-05-17 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210516_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
