# Generated by Django 3.0.6 on 2020-08-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bag', models.FloatField()),
                ('weight', models.FloatField()),
                ('product_condition', models.CharField(choices=[('Processed', 'Processed'), ('Un Processed', 'Un Processed')], default='Processed', max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name_of_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Rooms')),
            ],
        ),
    ]
