# Generated by Django 3.0.6 on 2021-05-23 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('hut_buy', '0001_initial'),
        ('vouchers', '0011_auto_20210523_2318'),
        ('LC', '0006_merge_20210522_1647'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_loss', models.FloatField(default=0)),
                ('seed_weight', models.FloatField(default=0)),
                ('spot_weight', models.FloatField(default=0)),
                ('seed_rate', models.FloatField(default=0)),
                ('spot_rate', models.FloatField(default=0)),
                ('number_of_bag', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.BuyVoucher')),
                ('hut_buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hut_buy.HutBuy')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LC.LC')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
