# Generated by Django 3.0.6 on 2021-11-09 16:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0026_auto_20211029_1216'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YardStock',
            new_name='Stock',
        ),
    ]
