# Generated by Django 3.1.1 on 2021-05-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_buyvoucher_date_time_stamp'),
        ('LC', '0006_merge_20210522_1647'),
        ('products', '0001_initial'),
        ('hut_buy', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='name_of_product',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='product_condition',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='weight',
        ),
        migrations.AddField(
            model_name='stocks',
            name='buy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.buyvoucher'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='hut_buy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hut_buy.hutbuy'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LC.lc'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='seed_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='seed_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='spot_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='spot_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='weight_loss',
            field=models.FloatField(default=0),
        ),
    ]
