# Generated by Django 3.2.8 on 2021-10-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0026_auto_20211029_1216'),
        ('products', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='product_name',
        ),
        migrations.AddField(
            model_name='stocks',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='voucher_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.buyvoucher'),
        ),
    ]
