# Generated by Django 3.0.6 on 2021-11-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardstock',
            name='remarks',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
