# Generated by Django 3.1.1 on 2021-05-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LC', '0005_auto_20210509_1230'),
        ('hut_buy', '0001_initial'),
        ('vouchers', '0009_buyvoucher_date_time_stamp'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='weight',
            new_name='seed_rate',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='name_of_product',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='product_condition',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='room_no',
        ),
        migrations.AddField(
            model_name='stocks',
            name='buy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vouchers.buyvoucher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='hut_buy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hut_buy.hutbuy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='lc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LC.lc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='product_name',
            field=models.CharField(choices=[('name', '')], default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='seed_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='spot_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='spot_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='weight_loss',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
