# Generated by Django 3.0.6 on 2021-11-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardstock',
            name='number_of_bag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
