# Generated by Django 3.0.6 on 2020-06-01 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='stocks',
            name='product_condition',
            field=models.CharField(choices=[('pr', 'Processed'), ('upr', 'Un Processed')], default='pr', max_length=50),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Rooms'),
        ),
    ]
