# Generated by Django 3.0.6 on 2020-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200601_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='product_condition',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Un Processed', 'Un Processed')], default='Processed', max_length=50),
        ),
    ]
