# Generated by Django 3.0.6 on 2021-11-09 16:18

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20211109_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='store_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, to='stocks.Store'),
        ),
    ]
