# Generated by Django 3.2.8 on 2021-11-10 09:27

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0006_auto_20211110_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='added_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
