# Generated by Django 3.2.8 on 2021-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stock_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='rate_per_mann',
            field=models.FloatField(default=0),
        ),
    ]
