# Generated by Django 3.2.8 on 2021-11-19 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('organizations', '0013_auto_20210919_2339'),
        ('vouchers', '0026_auto_20211029_1216'),
        ('stocks', '0011_stock_business_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='PreStock',
        ),
    ]
