# Generated by Django 3.2.8 on 2021-11-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0012_rename_stock_prestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestock',
            name='added_to_finished_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FinishedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_rate_per_kg', models.FloatField(default=0)),
                ('processing_cost_per_kg', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('date_time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('inventory_updated', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=225)),
                ('added_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_stock_added_by', to=settings.AUTH_USER_MODEL)),
                ('pre_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.prestock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='finished_stock_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'pre_stock')},
            },
        ),
    ]
