# Generated by Django 3.2.8 on 2021-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20211119_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedstock',
            name='number_of_bag',
            field=models.FloatField(default=0),
        ),
    ]
