# Generated by Django 3.2.8 on 2021-11-22 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0015_auto_20211119_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('processing_completed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=225)),
                ('added_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_stock_added_by', to=settings.AUTH_USER_MODEL)),
                ('pre_stocks', models.ManyToManyField(to='stocks.PreStock')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='processing_stock_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
