# Generated by Django 3.2.8 on 2021-11-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_processingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestock',
            name='added_to_processing_stock',
            field=models.BooleanField(default=False),
        ),
    ]
