# Generated by Django 3.2.8 on 2021-11-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_auto_20211123_1527'),
        ('stocks', '0017_prestock_added_to_processing_stock'),
    ]

    operations = [
    ]
