# Generated by Django 3.2.8 on 2021-12-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stocks', '0018_merge_20211123_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedstock',
            name='processing_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.processingstock'),
        ),
        migrations.AlterUniqueTogether(
            name='finishedstock',
            unique_together={('product', 'processing_stock')},
        ),
        migrations.RemoveField(
            model_name='finishedstock',
            name='pre_stock',
        ),
    ]
