# Generated by Django 3.2.8 on 2021-12-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stocks', '0019_auto_20211203_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('bags', models.FloatField(default=0)),
                ('processing_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.processingstock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products')),
            ],
        ),
    ]
