# Generated by Django 3.2.8 on 2021-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_poststock'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststock',
            name='rate_per_kg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
