# Generated by Django 3.2.8 on 2021-12-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_poststock_rate_per_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestock',
            name='business_name',
        ),
        migrations.AlterField(
            model_name='poststock',
            name='rate_per_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='poststock',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
