# Generated by Django 3.2.8 on 2021-12-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_auto_20211206_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestock',
            name='added_to_processing_stock',
        ),
    ]
