# Generated by Django 3.2.8 on 2021-12-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_alter_poststock_business_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedstock',
            old_name='buying_rate_per_kg',
            new_name='rate_per_kg',
        ),
    ]
