# Generated by Django 3.2.10 on 2021-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_rename_buying_rate_per_kg_finishedstock_rate_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststock',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
