# Generated by Django 3.2.10 on 2021-12-18 19:38

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_poststock_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststock',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.Empty, to='stocks.store'),
        ),
    ]
