# Generated by Django 3.2.10 on 2021-12-20 18:21

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_poststock_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststock',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.Empty, to='stocks.store'),
        ),
    ]
