# Generated by Django 3.2.10 on 2021-12-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_alter_poststock_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProcessingStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='processingstock',
            name='pre_stocks',
        ),
        migrations.AddField(
            model_name='processingstock',
            name='pre_processing_stocks',
            field=models.ManyToManyField(to='stocks.PreProcessingStock'),
        ),
    ]
