# Generated by Django 3.2.10 on 2022-01-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0031_auto_20211225_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessingstock',
            name='pre_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.prestock'),
            preserve_default=False,
        ),
    ]
