# Generated by Django 3.2.10 on 2022-01-07 17:46

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_preprocessingstock_pre_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='YardLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='processingstock',
            name='yard_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, to='stocks.yardlocation'),
        ),
    ]
