# Generated by Django 3.0.6 on 2020-05-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('product_name', 'product_category')},
        ),
    ]
